### ISSUE TITLE
Selected unread message font is not bold

### ISSUE THREAD

**Issue by laughedelic** [arimai/N1-BoraBora#1]
I have a setting to mark unread only manually. So when I navigate (2-column view) between unread messages, the selected one's text boldness gets canceled. 
I know that it's the same in the default theme, but there selection is blue and this is not so noticeable. In this theme, this looks a bit strange to me, like if the message was immediately marked as read. Could you change it?

Here are screenshots:
- not selected:
  <img width="390" alt="screen shot 2016-09-22 at 04 52 29" src="https://cloud.githubusercontent.com/assets/766656/18735723/6c711e8e-8080-11e6-8713-048fb576f3ce.png">
- selected (looks like read, but the blue dot shows that it's not):
  <img width="390" alt="screen shot 2016-09-22 at 04 50 39" src="https://cloud.githubusercontent.com/assets/766656/18735714/4947bd96-8080-11e6-8f69-295878d963c4.png">

**Comment by arimai** [comment]
Thats a nice catch! It looks better with bolder text.
I changed it to look like this:

<img width="468" alt="issue 1" src="https://cloud.githubusercontent.com/assets/20115943/18741185/95c3d93e-8062-11e6-89e8-8eded1d56e38.png">

You can get it from the new release. Thanks :)

**Comment by laughedelic** [comment]
Thanks!
